# Generated by Django 2.2.18 on 2024-10-23 15:40

from django.db import migrations
import qatrack.qatrack_core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20200722_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='filters',
            field=qatrack.qatrack_core.fields.JSONField(blank=True),
        ),
    ]
