language: python

python:
  - "2.6_with_system_site_packages"
  - "2.7_with_system_site_packages"

env:
  - DJANGO=1.6 DB=sqlite
  - DJANGO=1.6 DB=postgres
  - DJANGO=1.6 DB=mysql

before_script:
  - mysql -e "create database qatrackplus;"
  - mysql -e "GRANT ALL ON qatrackplus.* TO 'qatrackplus'@'localhost' IDENTIFIED BY 'qatrackplus';"
  - psql -c "create database qatrackplus;" -U postgres
  - psql -c "CREATE USER qatrackplus with PASSWORD 'qatrackplus';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE qatrackplus to qatrackplus;" -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

install:
  - if [[ $DB == mysql ]]; then pip install -q mysql-python --use-mirrors; fi
  - if [[ $DB == mysql ]]; then cp deploy/travis_mysql.py qatrack/local_settings.py; fi
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --use-mirrors; fi
  - if [[ $DB == postgres ]]; then cp deploy/travis_postgres.py qatrack/local_settings.py; fi
  - if [[ $DB == sqlite ]]; then cp deploy/travis_sqlite.py qatrack/local_settings.py; fi
  -  pip install -r requirements/base.txt --use-mirrors
  -  pip install -r requirements/optional.txt --use-mirrors

script:
  - python manage.py test
