# Generated by Django 2.2.18 on 2024-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_auto_20210323_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['number'], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.AddField(
            model_name='unit',
            name='room',
            field=models.CharField(blank=True, help_text='Optional Room information', max_length=256, null=True),
        ),
    ]
