# Generated by Django 2.2.18 on 2024-10-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0020_auto_20241023_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this department', max_length=64, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='Unique identifier made of lowercase characters and underscores for this dep', unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='unit',
            name='room',
        ),
        migrations.AddField(
            model_name='site',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.Department'),
        ),
    ]
