# Generated by Django 2.2.18 on 2024-10-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0021_auto_20241024_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name', 'department'), 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(help_text='Unique identifier made of lowercase characters and underscores for this site', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='site',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.Department', verbose_name='department'),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('name', 'department')},
        ),
    ]
