# Generated by Django 2.2.18 on 2024-10-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0022_auto_20241024_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('site', 'name'), 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.AddField(
            model_name='department',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.Site', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('site', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='site',
            name='department',
        ),
    ]
