# Generated by Django 2.2.18 on 2024-11-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_auto_20241024_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPart_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parts of a Unit (e.g. Tube)', max_length=64, unique=True, verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Unit Part',
                'verbose_name_plural': 'Unit Part',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='room',
            field=models.CharField(blank=True, help_text='Optional Room information', max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='UnitPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, help_text='Optional model name for this group', max_length=50, null=True, verbose_name='model name')),
                ('Serial_number', models.CharField(blank=True, help_text='part serial number', max_length=50, null=True, verbose_name='Serial Number')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.UnitPart_type', verbose_name='part type')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.Vendor', verbose_name='vendor')),
            ],
            options={
                'verbose_name': 'unit part',
                'verbose_name_plural': 'unit parts',
                'ordering': ('name',),
                'unique_together': {('name', 'vendor', 'model', 'Serial_number')},
            },
        ),
    ]
