# Generated by Django 2.2.18 on 2024-11-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0024_auto_20241107_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpart',
            options={'ordering': ('part_type',), 'verbose_name': 'unit part', 'verbose_name_plural': 'unit parts'},
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_parts',
            field=models.ManyToManyField(to='units.UnitPart'),
        ),
        migrations.AddField(
            model_name='unitpart',
            name='part_type',
            field=models.CharField(blank=True, help_text='Part type e.g. tube', max_length=50, null=True, verbose_name='part type'),
        ),
        migrations.AlterUniqueTogether(
            name='unitpart',
            unique_together={('part_type', 'vendor', 'model', 'Serial_number')},
        ),
        migrations.RemoveField(
            model_name='unitpart',
            name='name',
        ),
        migrations.DeleteModel(
            name='UnitPart_type',
        ),
    ]
