# Generated by Django 2.2.18 on 2024-11-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0025_auto_20241108_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_parts',
        ),
        migrations.AddField(
            model_name='unit',
            name='Units_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.UnitPart'),
        ),
    ]
