# Generated by Django 2.2.18 on 2024-11-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0026_auto_20241108_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='Units_parts',
        ),
        migrations.AddField(
            model_name='unitpart',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='units.Unit'),
        ),
    ]
