# Generated by Django 2.2.18 on 2024-11-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0027_auto_20241108_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpart',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='unitpart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='unitpart',
            name='Serial_number',
        ),
        migrations.RemoveField(
            model_name='unitpart',
            name='model',
        ),
        migrations.RemoveField(
            model_name='unitpart',
            name='vendor',
        ),
    ]
