# Generated by Django 2.2.18 on 2024-11-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0028_auto_20241108_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpart',
            options={'ordering': ('part_type',), 'verbose_name': 'unit part', 'verbose_name_plural': 'unit parts'},
        ),
        migrations.AddField(
            model_name='unitpart',
            name='Serial_number',
            field=models.CharField(blank=True, help_text='part serial number', max_length=50, null=True, verbose_name='Serial Number'),
        ),
        migrations.AddField(
            model_name='unitpart',
            name='model',
            field=models.CharField(blank=True, help_text='Optional model name for this group', max_length=50, null=True, verbose_name='model name'),
        ),
        migrations.AddField(
            model_name='unitpart',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units.Vendor', verbose_name='vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='unitpart',
            unique_together={('part_type', 'vendor', 'model', 'Serial_number')},
        ),
    ]
