# Generated by Django 2.2.18 on 2024-11-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0029_auto_20241108_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpart',
            options={'ordering': ('name',), 'verbose_name': 'unit part', 'verbose_name_plural': 'unit parts'},
        ),
        migrations.RenameField(
            model_name='unitpart',
            old_name='part_type',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='unitpart',
            unique_together={('name', 'vendor', 'model', 'Serial_number')},
        ),
    ]
