# Generated by Django 2.2.18 on 2024-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0059_test_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='body',
            field=models.BooleanField(default=False, help_text='Display this text in the body of reports', verbose_name='Test result in Report'),
        ),
        migrations.AlterField(
            model_name='test',
            name='summary',
            field=models.BooleanField(default=False, help_text='Display this text in the summary of reports', verbose_name='Test result in Report Summary'),
        ),
    ]
